travis:
  secure:
    BINSTAR_TOKEN: wdKZGNHOiXpFlunXOJyNDnP1G8mWH2rjKdpO/WWl9gflLz6A9y43t6MMrGtibYvEgLYTumTypbvl9lWrUY3cS3m0CuBL5HQ+JSmrT8EYB7F2lZkpbqw2TuaCp78SiNkGYDSC1NKrcD8Z2EuMX1qLphb7eLEEDBRopwtoal7NW7MThCkpnR1jtSZLF6Qfi8kJesgOKIWHVPOyWRs6UoQODmxplKVFGB4AWE6TMdN2NRce+O+x/3+ZHBuwCTzwk17XHBQhr/NHWu2Ls/75lsxhq2RbEyGpzjx990oVxzLnFJexVkacFFeih3ifBiNpxD0Vvjnm0Da6e2WVM8UvZx8X5MXzk9l+un3+t/+pgKXIds0BptGCnhfi336GN471vi9ocSTIeCNyyYQ06QrBNuhp2LnMe6/FM8dSRVRpThEG2An57zeCm7vMkYlghdI6vg6YPGj8LGLs6NaIQhGWUOQmzDOgb8IiXmHn73sY8ckrK6F+iuGtredi1PyiR90s7LUx9VD2Jb59zJ8/GlauwoVGbkVfY2NKUBNlZATdWRVMVWdWbC3rISgLi0ADpmfT93mYgHoOlf5pddUZI3JXqkOAKLFg4i0jpLzONOSeesfPOcvwatMdgyMJM9uDt3/hygKq3QbAo5J/O6qFLwFKzl0yeeRT68SZIDpZiNEDk2rYnBI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
